-- Create a bucket for images
insert into storage.buckets (id, name, public) values ('memories', 'memories', true);

-- Create memories table
create table public.memories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text not null,
  remark text,
  date date,
  user_id uuid references auth.users default auth.uid()
);

-- Enable RLS
alter table public.memories enable row level security;

-- Policy to allow authenticated users to view all memories (Since it's just 2 of you)
create policy "Enable read access for all users"
on public.memories for select
to authenticated
using (true);

-- Policy to allow authenticated users to insert
create policy "Enable insert for authenticated users"
on public.memories for insert
to authenticated
with check (true);

-- Policy to allow authenticated users to delete their own memories
create policy "Enable delete for users based on user_id"
on public.memories for delete
to authenticated
using (auth.uid() = user_id);

-- Storage policies
create policy "Give users access to own folder 1bk0z_0" ON storage.objects FOR SELECT TO public USING (bucket_id = 'memories');
create policy "Give users access to own folder 1bk0z_1" ON storage.objects FOR INSERT TO public WITH CHECK (bucket_id = 'memories');
